// Code generated by protoc-gen-go. DO NOT EDIT.
// source: farmer/farmer.proto

package fap_micro_srv_farmer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Farmer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsEnabled            bool     `protobuf:"varint,5,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Image                []*Image `protobuf:"bytes,8,rep,name=image,proto3" json:"image,omitempty"`
	IsConfirmed          bool     `protobuf:"varint,9,opt,name=isConfirmed,proto3" json:"isConfirmed,omitempty"`
	IsVerified           bool     `protobuf:"varint,10,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	Quantity             int32    `protobuf:"varint,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Farmer) Reset()         { *m = Farmer{} }
func (m *Farmer) String() string { return proto.CompactTextString(m) }
func (*Farmer) ProtoMessage()    {}
func (*Farmer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{0}
}

func (m *Farmer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Farmer.Unmarshal(m, b)
}
func (m *Farmer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Farmer.Marshal(b, m, deterministic)
}
func (m *Farmer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Farmer.Merge(m, src)
}
func (m *Farmer) XXX_Size() int {
	return xxx_messageInfo_Farmer.Size(m)
}
func (m *Farmer) XXX_DiscardUnknown() {
	xxx_messageInfo_Farmer.DiscardUnknown(m)
}

var xxx_messageInfo_Farmer proto.InternalMessageInfo

func (m *Farmer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Farmer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Farmer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Farmer) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Farmer) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *Farmer) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Farmer) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Farmer) GetImage() []*Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Farmer) GetIsConfirmed() bool {
	if m != nil {
		return m.IsConfirmed
	}
	return false
}

func (m *Farmer) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Farmer) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Order                int32    `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Image) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Image) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool      `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Farmer               *Farmer   `protobuf:"bytes,2,opt,name=farmer,proto3" json:"farmer,omitempty"`
	Farmers              []*Farmer `protobuf:"bytes,3,rep,name=farmers,proto3" json:"farmers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetFarmer() *Farmer {
	if m != nil {
		return m.Farmer
	}
	return nil
}

func (m *Response) GetFarmers() []*Farmer {
	if m != nil {
		return m.Farmers
	}
	return nil
}

func init() {
	proto.RegisterType((*Farmer)(nil), "fap.micro.srv.farmer.Farmer")
	proto.RegisterType((*Image)(nil), "fap.micro.srv.farmer.Image")
	proto.RegisterType((*GetRequest)(nil), "fap.micro.srv.farmer.GetRequest")
	proto.RegisterType((*Response)(nil), "fap.micro.srv.farmer.Response")
}

func init() { proto.RegisterFile("farmer/farmer.proto", fileDescriptor_ceb4f917f19c5880) }

var fileDescriptor_ceb4f917f19c5880 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x26, 0xe9, 0x26, 0x4d, 0x26, 0x0b, 0x07, 0xb3, 0x07, 0x6b, 0x59, 0xad, 0xa2, 0x9c, 0x72,
	0x0a, 0xa2, 0x20, 0xee, 0x68, 0x05, 0x2b, 0x2e, 0x20, 0x19, 0xc1, 0xdd, 0x5b, 0x4f, 0xc0, 0xd2,
	0xe6, 0xa7, 0xb6, 0x5b, 0xd4, 0xd7, 0xe0, 0x49, 0x78, 0x0d, 0xde, 0x0a, 0x65, 0x9c, 0xb4, 0x3d,
	0x44, 0xdd, 0x53, 0xe6, 0xfb, 0xf1, 0x8c, 0xe7, 0x4b, 0x02, 0x2f, 0x6b, 0x69, 0x1a, 0x34, 0xaf,
	0xfd, 0xa3, 0xea, 0x4d, 0xe7, 0x3a, 0x76, 0x55, 0xcb, 0xbe, 0x6a, 0xf4, 0xda, 0x74, 0x95, 0x35,
	0xbb, 0xca, 0x6b, 0xc5, 0xbf, 0x10, 0xe2, 0x4f, 0x54, 0xb2, 0x17, 0x10, 0x6a, 0xc5, 0x83, 0x3c,
	0x28, 0x53, 0x11, 0x6a, 0xc5, 0x18, 0x5c, 0xb4, 0xb2, 0x41, 0x1e, 0x12, 0x43, 0x35, 0xbb, 0x82,
	0x08, 0x1b, 0xa9, 0x1f, 0xf9, 0x82, 0x48, 0x0f, 0xd8, 0x35, 0x24, 0xbd, 0xb4, 0xf6, 0x77, 0x67,
	0x14, 0xbf, 0x20, 0xe1, 0x80, 0xd9, 0x0d, 0xa4, 0xda, 0x7e, 0x6c, 0xe5, 0xc3, 0x23, 0x2a, 0x1e,
	0xe5, 0x41, 0x99, 0x88, 0x23, 0x31, 0xa8, 0x6b, 0x83, 0xd2, 0xa1, 0xfa, 0xe0, 0x78, 0x4c, 0x47,
	0x8f, 0xc4, 0xa0, 0x6e, 0x7b, 0x35, 0xaa, 0x4b, 0xaf, 0x1e, 0x08, 0xf6, 0x06, 0x22, 0xdd, 0xc8,
	0x9f, 0xc8, 0x93, 0x7c, 0x51, 0x66, 0xab, 0x57, 0xd5, 0xdc, 0x82, 0xd5, 0xe7, 0xc1, 0x22, 0xbc,
	0x93, 0xe5, 0x90, 0x69, 0x7b, 0xd7, 0xb5, 0xb5, 0x36, 0x0d, 0x2a, 0x9e, 0xd2, 0x75, 0x4e, 0x29,
	0x76, 0x0b, 0xa0, 0xed, 0x0f, 0x34, 0xba, 0xd6, 0xa8, 0x38, 0x90, 0xe1, 0x84, 0x19, 0x56, 0xdd,
	0x6c, 0x65, 0xeb, 0xb4, 0xdb, 0xf3, 0x2c, 0x0f, 0xca, 0x48, 0x1c, 0x70, 0xf1, 0x1d, 0x22, 0x9a,
	0x36, 0x97, 0x64, 0x2f, 0xdd, 0xaf, 0x29, 0xc9, 0xa1, 0x1e, 0x38, 0xb7, 0xef, 0x71, 0x0c, 0x92,
	0xea, 0x21, 0xdd, 0xce, 0x28, 0x34, 0x14, 0x62, 0x24, 0x3c, 0x28, 0x2e, 0x01, 0xee, 0xd1, 0x09,
	0xdc, 0x6c, 0xd1, 0xba, 0xe2, 0x4f, 0x00, 0x89, 0x40, 0xdb, 0x77, 0xad, 0x45, 0xc6, 0x61, 0x39,
	0xa6, 0x45, 0xd3, 0x12, 0x31, 0x41, 0xf6, 0x0e, 0x62, 0x1f, 0x00, 0x0d, 0xcd, 0x56, 0x37, 0xf3,
	0xe9, 0xf8, 0x57, 0x2f, 0x46, 0x2f, 0x7b, 0x0f, 0x4b, 0x5f, 0x59, 0xbe, 0xa0, 0x50, 0xcf, 0x1f,
	0x9b, 0xcc, 0xab, 0xbf, 0x01, 0x3c, 0xf7, 0xdc, 0x37, 0x34, 0x3b, 0xbd, 0x46, 0xf6, 0x05, 0x2e,
	0xef, 0xe8, 0x2a, 0xe3, 0xc7, 0x75, 0xb6, 0xd1, 0xf5, 0xed, 0xbc, 0x3a, 0xed, 0x59, 0x3c, 0x63,
	0x5f, 0x21, 0xbd, 0x47, 0x37, 0x36, 0xcb, 0xe7, 0xed, 0xc7, 0x94, 0x9e, 0x6e, 0xf8, 0x10, 0xd3,
	0x5f, 0xf1, 0xf6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x27, 0x2e, 0x59, 0x2c, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FarmerService service

type FarmerServiceClient interface {
	CreateFarmer(ctx context.Context, in *Farmer, opts ...client.CallOption) (*Response, error)
	GetFarmer(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type farmerServiceClient struct {
	c           client.Client
	serviceName string
}

func NewFarmerServiceClient(serviceName string, c client.Client) FarmerServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "fap.micro.srv.farmer"
	}
	return &farmerServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *farmerServiceClient) CreateFarmer(ctx context.Context, in *Farmer, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FarmerService.CreateFarmer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmerServiceClient) GetFarmer(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FarmerService.GetFarmer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FarmerService service

type FarmerServiceHandler interface {
	CreateFarmer(context.Context, *Farmer, *Response) error
	GetFarmer(context.Context, *GetRequest, *Response) error
}

func RegisterFarmerServiceHandler(s server.Server, hdlr FarmerServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FarmerService{hdlr}, opts...))
}

type FarmerService struct {
	FarmerServiceHandler
}

func (h *FarmerService) CreateFarmer(ctx context.Context, in *Farmer, out *Response) error {
	return h.FarmerServiceHandler.CreateFarmer(ctx, in, out)
}

func (h *FarmerService) GetFarmer(ctx context.Context, in *GetRequest, out *Response) error {
	return h.FarmerServiceHandler.GetFarmer(ctx, in, out)
}
