// Code generated by protoc-gen-go. DO NOT EDIT.
// source: farmer/farmer.proto

package fap_micro_srv_farmer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Farmer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsEnabled            bool     `protobuf:"varint,5,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Image                []*Image `protobuf:"bytes,8,rep,name=image,proto3" json:"image,omitempty"`
	IsConfirmed          bool     `protobuf:"varint,9,opt,name=isConfirmed,proto3" json:"isConfirmed,omitempty"`
	IsVerified           bool     `protobuf:"varint,10,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Farmer) Reset()         { *m = Farmer{} }
func (m *Farmer) String() string { return proto.CompactTextString(m) }
func (*Farmer) ProtoMessage()    {}
func (*Farmer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{0}
}

func (m *Farmer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Farmer.Unmarshal(m, b)
}
func (m *Farmer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Farmer.Marshal(b, m, deterministic)
}
func (m *Farmer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Farmer.Merge(m, src)
}
func (m *Farmer) XXX_Size() int {
	return xxx_messageInfo_Farmer.Size(m)
}
func (m *Farmer) XXX_DiscardUnknown() {
	xxx_messageInfo_Farmer.DiscardUnknown(m)
}

var xxx_messageInfo_Farmer proto.InternalMessageInfo

func (m *Farmer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Farmer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Farmer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Farmer) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Farmer) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *Farmer) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Farmer) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Farmer) GetImage() []*Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Farmer) GetIsConfirmed() bool {
	if m != nil {
		return m.IsConfirmed
	}
	return false
}

func (m *Farmer) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Order                int32    `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Image) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Image) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Farmer               *Farmer  `protobuf:"bytes,2,opt,name=farmer,proto3" json:"farmer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ceb4f917f19c5880, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetFarmer() *Farmer {
	if m != nil {
		return m.Farmer
	}
	return nil
}

func init() {
	proto.RegisterType((*Farmer)(nil), "fap.micro.srv.farmer.Farmer")
	proto.RegisterType((*Image)(nil), "fap.micro.srv.farmer.Image")
	proto.RegisterType((*Response)(nil), "fap.micro.srv.farmer.Response")
}

func init() { proto.RegisterFile("farmer/farmer.proto", fileDescriptor_ceb4f917f19c5880) }

var fileDescriptor_ceb4f917f19c5880 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0x6f, 0xd3, 0x26, 0x4d, 0xa7, 0xf7, 0xde, 0x85, 0xe9, 0xc2, 0x2a, 0x55, 0x15, 0x65,
	0xd5, 0x55, 0x10, 0x85, 0x17, 0x40, 0x15, 0x48, 0x6c, 0x58, 0x04, 0xc1, 0x82, 0x0d, 0x72, 0xeb,
	0x09, 0x58, 0x6a, 0x62, 0xcb, 0x0e, 0x45, 0x3c, 0x14, 0xef, 0x88, 0x32, 0x4e, 0x7f, 0x16, 0x11,
	0xab, 0xcc, 0x7c, 0x67, 0x72, 0xe2, 0x39, 0x0e, 0x9c, 0x15, 0xc2, 0x96, 0x68, 0x2f, 0xfc, 0x23,
	0x33, 0x56, 0xd7, 0x9a, 0x4d, 0x0a, 0x61, 0xb2, 0x52, 0x6d, 0xac, 0xce, 0x9c, 0xdd, 0x65, 0x5e,
	0x4b, 0xbf, 0x03, 0x88, 0xee, 0xa8, 0x64, 0xff, 0x21, 0x50, 0x92, 0xf7, 0x92, 0xde, 0x62, 0x94,
	0x07, 0x4a, 0x32, 0x06, 0x83, 0x4a, 0x94, 0xc8, 0x03, 0x22, 0x54, 0xb3, 0x09, 0x84, 0x58, 0x0a,
	0xb5, 0xe5, 0x7d, 0x82, 0xbe, 0x61, 0x53, 0x88, 0x8d, 0x70, 0xee, 0x53, 0x5b, 0xc9, 0x07, 0x24,
	0x1c, 0x7a, 0x36, 0x83, 0x91, 0x72, 0xb7, 0x95, 0x58, 0x6f, 0x51, 0xf2, 0x30, 0xe9, 0x2d, 0xe2,
	0xfc, 0x08, 0x1a, 0x75, 0x63, 0x51, 0xd4, 0x28, 0x6f, 0x6a, 0x1e, 0xd1, 0xab, 0x47, 0xd0, 0xa8,
	0x1f, 0x46, 0xb6, 0xea, 0xd0, 0xab, 0x07, 0xc0, 0x2e, 0x21, 0x54, 0xa5, 0x78, 0x43, 0x1e, 0x27,
	0xfd, 0xc5, 0x78, 0x79, 0x9e, 0x75, 0x2d, 0x98, 0xdd, 0x37, 0x23, 0xb9, 0x9f, 0x64, 0x09, 0x8c,
	0x95, 0x5b, 0xe9, 0xaa, 0x50, 0xb6, 0x44, 0xc9, 0x47, 0x74, 0x9c, 0x53, 0xc4, 0xe6, 0x00, 0xca,
	0x3d, 0xa3, 0x55, 0x85, 0x42, 0xc9, 0x81, 0x06, 0x4e, 0x48, 0xfa, 0x04, 0x21, 0x39, 0x76, 0xa5,
	0x65, 0x44, 0xfd, 0xbe, 0x4f, 0xab, 0xa9, 0x1b, 0x56, 0x7f, 0x19, 0x6c, 0xc3, 0xa2, 0xba, 0x49,
	0x50, 0x5b, 0x89, 0x96, 0x82, 0x0a, 0x73, 0xdf, 0xa4, 0x2f, 0x10, 0xe7, 0xe8, 0x8c, 0xae, 0x1c,
	0x32, 0x0e, 0xc3, 0x36, 0x02, 0xb2, 0x8f, 0xf3, 0x7d, 0xcb, 0xae, 0x21, 0xf2, 0x5b, 0xd1, 0x57,
	0xc6, 0xcb, 0x59, 0xf7, 0xca, 0xfe, 0x3e, 0xf3, 0x76, 0x76, 0xf9, 0x0a, 0xff, 0x3c, 0x79, 0x44,
	0xbb, 0x53, 0x1b, 0x64, 0x0f, 0xf0, 0x77, 0x45, 0x8e, 0xed, 0xc5, 0xff, 0x6a, 0x33, 0x9d, 0x77,
	0xab, 0xfb, 0xe3, 0xa6, 0x7f, 0xd6, 0x11, 0xfd, 0x60, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x95, 0x46, 0xbc, 0xfa, 0x77, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FarmerServiceClient is the client API for FarmerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FarmerServiceClient interface {
	CreateFarmer(ctx context.Context, in *Farmer, opts ...grpc.CallOption) (*Response, error)
}

type farmerServiceClient struct {
	cc *grpc.ClientConn
}

func NewFarmerServiceClient(cc *grpc.ClientConn) FarmerServiceClient {
	return &farmerServiceClient{cc}
}

func (c *farmerServiceClient) CreateFarmer(ctx context.Context, in *Farmer, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/fap.micro.srv.farmer.FarmerService/CreateFarmer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FarmerServiceServer is the server API for FarmerService service.
type FarmerServiceServer interface {
	CreateFarmer(context.Context, *Farmer) (*Response, error)
}

func RegisterFarmerServiceServer(s *grpc.Server, srv FarmerServiceServer) {
	s.RegisterService(&_FarmerService_serviceDesc, srv)
}

func _FarmerService_CreateFarmer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Farmer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmerServiceServer).CreateFarmer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fap.micro.srv.farmer.FarmerService/CreateFarmer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmerServiceServer).CreateFarmer(ctx, req.(*Farmer))
	}
	return interceptor(ctx, in, info, handler)
}

var _FarmerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fap.micro.srv.farmer.FarmerService",
	HandlerType: (*FarmerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFarmer",
			Handler:    _FarmerService_CreateFarmer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "farmer/farmer.proto",
}
